finder/urls.py
from django.conf.urls import url

from . import views

app_name = "finder"

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # RESOURCES
    url(r'^new-resources/$', views.AddResourcesView.as_view(), name='add_resources'),
    url(r'^resources/(?P<pk>[0-9]+)/$', views.ResourcesDetails.as_view(), name='resources_details'),
    url(r'list-resources/$', views.ResourcesList.as_view(), name="resources_list"),
    url(r'^delete-resources/(?P<resources_id>[0-9]+)/$', views.delete_resources, name="delete_resources"),

    # RESOURCES PROPER
    url(r'^(?P<resources_id>[0-9]+)/add_proper/$', views.add_resources_proper, name='add_resources_proper'),
    url(r'^delete-resources-proper/(?P<proper_id>[0-9]+)/$', views.delete_resources_proper, name="delete_resources_proper"),

    #SEARCH
    url(r'^search/$', views.search, name='search'),

    #USER RESOURCES
    url(r'^add-user-resources/(?P<resources_id>[0-9]+)/$', views.add_user_resources, name="add_user_resources"),
    url(r'^delete-user-resources/(?P<uR_id>[0-9]+)/$', views.delete_user_resources, name="delete_user_resources"),

    # USER
    url(r'^create-user', views.CreateUserView.as_view(), name="create_user"),
    url(r'^list-users/$', views.UserListView.as_view(), name='users_list'),
    url(r'^user/(?P<pk>[0-9]+)/$', views.UserView.as_view(), name="user_details"),
    url(r'^delete-user/(?P<user_id>[0-9]+)/$', views.delete_user, name='delete_user'),

    # USER QUALITY
    url(r'^(?P<user_id>[0-9]+)/add-quality/$', views.add_user_quality, name='add_user_quality'),
    url(r'^delete-quality/(?P<user_quality_id>[0-9]+)/$', views.delete_user_quality, name='delete_user_quality'),

]

magus/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^finder/', include('finder.urls')),
    url(r'^admin/', admin.site.urls),
]

finder/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserQuality(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.CharField(max_length=200)


class Resources(models.Model):
    name = models.CharField(max_length = 200)
    date_in = models.DateField('bekerulesi ido')
    date_out = models.DateField('kikerulesi ido')
    date_out.null = True
    date_out.blank = True


class ResourcesProper(models.Model):
    resources = models.ForeignKey(Resources, on_delete=models.CASCADE)
    key = models.CharField(max_length=200)
    value = models.CharField(max_length=200, default=None)


class UserResources(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.ForeignKey(Resources, on_delete=models.CASCADE)

finder/forms.py
from django import forms
from finder.models import Resources
from django.contrib.auth.models import User

class ResourcesForm(forms.Form):
    name = forms.CharField()
    name.widget.attrs['class'] = 'form-control'

    date_in = forms.DateField()
    date_in.widget.input_type = 'date'
    date_in.widget.attrs['class'] = 'form-control'

    date_out = forms.DateField(required=False)
    date_out.widget.input_type = 'date'
    date_out.widget.attrs['class'] = 'form-control'

    def saveData(self):
        resources = Resources()
        resources.name = self.cleaned_data.get('name')
        resources.date_in = self.cleaned_data.get('date_in')
        resources.date_out = self.cleaned_data.get('date_out')
        resources.save()
        return resources


class CreateUserForm(forms.Form):
    username = forms.CharField()
    username.widget.attrs['class'] = 'form-control'

    email = forms.EmailField()
    email.widget.attrs['class'] = 'form-control'

    password1 = forms.CharField(widget=forms.PasswordInput(), label="Password")
    password1.widget.attrs['class'] = 'form-control'

    password2 = forms.CharField(widget=forms.PasswordInput(), label="Password Confirm")
    password2.widget.attrs['class'] = 'form-control'

    first_name = forms.CharField()
    first_name.widget.attrs['class'] = 'form-control'

    last_name = forms.CharField()
    last_name.widget.attrs['class'] = 'form-control'

    def clean_username(self):
        try:
            User.objects.get(username=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']

        raise forms.ValidationError("this user exist already")

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords dont match each other")

        return self.cleaned_data

    def saveData(self):
        user = User.objects.create_user(username=self.cleaned_data['username'],
                                            password=self.cleaned_data['password1'],
                                            email=self.cleaned_data['email'],
                                            )
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

finder/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from finder.forms import ResourcesForm, CreateUserForm
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from .models import Resources,UserResources, UserQuality
from finder.models import ResourcesProper

# Create your views here.


class UserView(generic.DetailView):
    model = User
    template_name = 'finder/user.html'


class UserListView(generic.ListView):
    template_name = "finder/users_list.html"
    context_object_name = 'users'

    def get_queryset(self):
        return User.objects.all()


class AddResourcesView(generic.FormView):
    template_name = 'finder/new_resources.html'
    form_class = ResourcesForm
    success_url = 'finder/list-resources/'

    def form_valid(self, form):
        resources = form.saveData()
        return super().form_valid(form)


class CreateUserView(generic.FormView):
    template_name = 'finder/create_user.html'
    form_class = CreateUserForm
    success_url = '/finder/list-users/'

    def form_valid(self, form):
        user = form.saveData()
        return super().form_valid(form)


class ResourcesDetails(generic.DetailView):
    model = Resources
    template_name = 'finder/resources.html'

    def get_context_data(self, **kwargs):
        context = super(ResourcesDetails, self).get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context

class ResourcesList(generic.ListView):
    template_name = "finder/resources_list.html"
    context_object_name = 'resources'

    def get_queryset(self):
        return Resources.objects.all()


def add_user_resources(request, resources_id):
    user = get_object_or_404(User, pk=request.POST['user_id'])
    resources = get_object_or_404(Resources, pk=resources_id)
    user_resources = UserResources()
    user_resources.user = user
    user_resources.value = resources
    user_resources.save()

    return HttpResponseRedirect(reverse('finder:resources_details', args=(resources_id,)))


def add_resources_proper(request, resources_id):
    resources = get_object_or_404(Resources, pk=resources_id)
    r_proper = ResourcesProper()
    r_proper.resources = resources
    key = request.POST['key']
    value = request.POST['value']
    if(key.replace(" ", "") != "" or value.replace(" ", "") != ""):
        r_proper.key = request.POST['key']
        r_proper.value = request.POST['value']
        r_proper.save()

    return HttpResponseRedirect(reverse('finder:resources_details', args=(resources_id,)))

def add_user_quality(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    u_quality = UserQuality()
    u_quality.user = user
    value = request.POST['value']
    if(value.replace(" ", "") != ""):
        u_quality.value = request.POST['value']
        u_quality.save()

    return HttpResponseRedirect(reverse('finder:user_details', args=(user_id,)))


def delete_user_quality(request, user_quality_id):
    user_quality = get_object_or_404(UserQuality, pk=user_quality_id)
    user_id = user_quality.user.pk
    user_quality.delete()
    return HttpResponseRedirect(reverse('finder:user_details', args=(user_id,)))


def delete_resources_proper(request, proper_id):
    r_proper = get_object_or_404(ResourcesProper, pk=proper_id)
    resources_id = r_proper.resources.pk
    r_proper.delete()

    return HttpResponseRedirect(reverse('finder:resources_details', args=(resources_id,)))


def delete_resources(request, resources_id):
    resources = get_object_or_404(Resources, pk= resources_id)
    resources.delete()
    return HttpResponseRedirect(reverse('finder:resources_list'))


def delete_user_resources(request, uR_id):
    user_resources = get_object_or_404(UserResources, pk = uR_id)
    resources_id = user_resources.value.pk
    user_resources.delete()
    return HttpResponseRedirect(reverse('finder:resources_details', args=(resources_id,)))


def delete_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if(user.is_superuser == 0):
        user.delete()
    return HttpResponseRedirect(reverse('finder:users_list'))


def index(request):
    return render(request,'finder/index.html',)

def search(request):
    resourcesPropers = ResourcesProper.objects.filter(value__contains=request.POST['text'])

    userQualities = UserQuality.objects.filter(value__contains=request.POST['text'])

    userNames = User.objects.filter(username__contains=request.POST['text'])
    userEmails = User.objects.filter(email__contains=request.POST['text'])

    data = {}
    resourcesP = {}
    users = {}

    for rP in resourcesPropers:
        resourcesP[rP.pk] = {
            'name': rP.resources.name,
            'id': rP.resources.pk,
            'key': rP.key,
            'value': rP.value
        }

    data['resources'] = resourcesP

    for uQ in userQualities:
        if uQ.user.first_name != "" and uQ.user.last_name != "":
            name = uQ.user.first_name + " " + uQ.user.last_name
        else:
            name = uQ.user.username
        users[uQ.pk] = {
            'name': name,
            'id': uQ.user.pk,
            'key': 'quality',
            'value': uQ.value
        }

    for uQ in userNames:
        if uQ.first_name != "" and uQ.last_name != "":
            name = uQ.first_name + " " + uQ.last_name
        else:
            name = uQ.username
        users[uQ.pk] = {
            'name': name,
            'id': uQ.pk,
            'key': 'username',
            'value': uQ.username
        }

    for uQ in userEmails:
        if uQ.first_name != "" and uQ.last_name != "":
            name = uQ.first_name + " " + uQ.last_name
        else:
            name = uQ.username
        users[uQ.pk] = {
            'name': name,
            'id': uQ.pk,
            'key': 'email',
            'value': uQ.email
        }

    data['users'] = users;

    return JsonResponse(data)

finder/templates/finder/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    {% load static %}

    <script src="{% static 'finder/jquery.cookie.js' %}"></script>
    <script src="{% static 'finder/resources.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Magus</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'finder:index' %}">Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Resources <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'finder:add_resources' %}">Add new</a></li>
                        <li><a href="{% url 'finder:resources_list' %}">List all</a></li>
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Users <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'finder:create_user' %}">Create User</a></li>
                        <li><a href="{% url 'finder:users_list' %}">List all</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <form class="navbar-form navbar-left">

                </form>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    {% block content%} {% endblock %}
</div>

</body>
</html>

finder/templates/finder/create_user.html
{% extends "finder/base.html" %}

{% block title %}New Resources{% endblock %}

{% block content %}
{% if form.errors %}

<p><strong>{{form.errors}}</strong></p> {% endif %}
<div class="col-md-6">
    <form method="post" action="{% url 'finder:create_user'%}">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <button type="submit" class="btn btn-success">Add</button>
    </form>
</div>
{% endblock %}

finder/templates/finder/index.html
{% extends "finder/base.html" %}

{% block title %}Magus{% endblock %}

{% block content %}
    <h1>Welcome, feel free for search</h1>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="Search" id="search">
        <br>
                    <div id="results_count"></div>

        <div id="results" class="list-group">
        </div>
    </div>
{% endblock %}

finder/templates/finder/new_resources.html
{% extends "finder/base.html" %}

{% block title %}New Resources{% endblock %}

{% block content %}
{% if form.errors %}

<p><strong>{{form.errors}}</strong></p> {% endif %}
<div class="col-md-6">
    <form method="post" action="{% url 'finder:add_resources'%}">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <button type="submit" class="btn btn-success">Add</button>
    </form>
</div>
{% endblock %}

finder/templates/finder/resources.html
{% extends "finder/base.html" %}

{% block title %}{{ resources.name }} details - MAGUS{% endblock %}

{% block content %}
    <h1>
        {{ resources.name }} resources details
        <a href="{% url 'finder:delete_resources' resources.pk%}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
    </h1>

    <div class="col-md-6">
        <h2>Name: {{resources.name}} </h2>
        <h2>Date in: {{ resources.date_in}} </h2>
        <h2>Date out: {%if resources.date_out != None %} {{ resources.date_out}} {%else%} Still in the company {%endif%}</h2>
    </div>

    <div class="col-md-6">
        <h2>Assigne to</h2>
        {%if resources.userresources_set.all.count > 0 %}
            {%for uR in resources.userresources_set.all %}
                {{uR.user.username}}
                    <a href="{% url 'finder:delete_user_resources' uR.pk%}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
            {% endfor %}
        {%else%}
        <br>
        <form method="post" action="{% url 'finder:add_user_resources' resources.pk%}">
            {% csrf_token %}
            <select name="user_id" class="form-control">
            {% for user in users %}
            <option value="{{user.pk}}">{{user.username}}</option>
            {%endfor%}
            </select>
            <br>
            <button type="submit" class="btn btn-success">Assigne</button>
        </form>
        {%endif%}
    </div>

    <div class="col-md-12">
    <ul>
        {%for rP in resources.resourcesproper_set.all%}
        <li>
            {{rP.key}}:
            {{rP.value}}
            <a href="{% url 'finder:delete_resources_proper' rP.pk %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
        </li>

        {% endfor %}
    </ul>

    <div id="new_resources_container" hidden>
        <div class="col-md-4">
            <form method="post" action="{% url 'finder:add_resources_proper' resources.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="key">Key</label>
                    <input type="text" class="form-control" name="key" id="key">
                </div>

                <div class="form-group">
                    <label for="value">Value</label>
                    <input type="text" class="form-control" name="value" id="value">
                </div>

                <button class="btn btn-success" id="add_proper">Add</button>
            </form>

        </div>
    </div>

    <br>
    <button class="btn btn-default" id="add_resources_proper">Add proper</button>
    </div>
{% endblock %}

finder/templates/finder/resources_list.html
{% extends "finder/base.html" %}

{% block title %}Resources List - MAGUS{% endblock %}

{% block content %}
    <div class="list-group">
    {% for r in resources %}
      <a class="list-group-item" href="{% url 'finder:resources_details' r.pk %}">{{r.name}}</a>
    {% endfor %}
    </div>
{% endblock %}

finder/templates/finder/user.html
{% extends "finder/base.html" %}

{% block title %}{{ user.username }} user - MAGUS{% endblock %}

{% block content %}
    <h1>
        {% if user.first_name != "" and user.last_name != ""%}
            {{user.first_name}} {{user.last_name}}
        {%else %}
            {{ user.username }}
        {%endif%}
        details
        {% if user.is_superuser == 0%}
        <a href="{% url 'finder:delete_user' user.pk %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
        {% endif %}
    </h1>

    <div class="col-md-6">
        {% if user.first_name != "" and user.last_name != ""%}
        <h2>Name: {{user.first_name}} {{user.last_name}} </h2>
        {%endif%}
        <h2>Username: {{user.username}} </h2>
        <h2>Email: {{ user.email}} </h2>
    </div>

    <div class="col-md-6">
        <h2>Assigne to</h2>
            {%for uR in user.userresources_set.all %}
                {{uR.value.name}}
                    <a href="{% url 'finder:delete_user_resources' uR.pk%}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
            {% endfor %}
        <br>

    </div>

    <div class="col-md-12">
    <ul>
        {%for rP in user.userquality_set.all%}
        <li>
            {{rP.value}}
            <a href="{% url 'finder:delete_user_quality' rP.pk%}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
        </li>

        {% endfor %}
    </ul>

    <div id="new_resources_container" hidden>
        <div class="col-md-4">
            <form method="post" action="{% url 'finder:add_user_quality' user.pk %}">
                {% csrf_token %}

                <div class="form-group">
                    <label for="value">Quality</label>
                    <input type="text" class="form-control" name="value" id="value">
                </div>

                <button class="btn btn-success" id="add_proper" type="submit">Add</button>
            </form>

        </div>
    </div>

    <br>
    <button class="btn btn-default" id="add_resources_proper">Add proper</button>
    </div>
{% endblock %}

finder/templates/finder/users_list.html
{% extends "finder/base.html" %}

{% block title %}Users List - MAGUS{% endblock %}

{% block content %}
    <div class="list-group">
    {% for u in users %}
      <a class="list-group-item" href="{% url 'finder:user_details' u.pk %}">
        {% if u.first_name != "" and u.last_name != ""%}
            {{u.first_name}} {{u.last_name}}
        {%else %}
            {{ u.username }}
        {%endif%}
      </a>
    {% endfor %}
    </div>
{% endblock %}